### PR TITLE
Make validate support optional fields

### PR DESCRIPTION
**Pull request by mmikulicic**

### CODE REVIEW

**Comment by dcodeIO** [comment]
Optional fields should already be checked [here](https://github.com/dcodeIO/protobuf.js/blob/master/src/verify.js#L270) when present.

**Comment by mmikulicic** [comment]
yes I added this check because that generated function was entered with m == null when an optional field was omitted. or at least the stack trace said that null has no such property. afk atm, I can attach a failing case when I'm back

**Comment by dcodeIO** [comment]
I assume that the `null` value there is representing an optional message. I added a commit above, give it a try when you're back.

**Comment by mmikulicic** [comment]
I confirm that `master` no longer exhibits the issue, abandoning this PR. Thank you!

**Pull request closed without merging**
