### PR TITLE
Port ReDoS vulnerability fix to Protobuf.js 5

### PR DESCRIPTION
**Pull request by murgatroid99**
I have a dependency on Protobuf.js 5 that I can't upgrade to Protobuf.js 6, so I would appreciate if this change would get merged and published in a patch release.

### CODE REVIEW

**Comment by dcodeIO** [comment]
Thanks, seems reasonable!

**Comment by murgatroid99** [comment]
Would you like me to send you a PR with a version bump?

**Comment by murgatroid99** [comment]
Ping. Would you mind publishing the package from this branch?

**Comment by nicolasnoble** [comment]
@yelworc we're contacting the security team to make sure this is updated.

**Pull request merged**
