### PR TITLE
including any.proto since it is referenced in type.proto

### PR DESCRIPTION
**Pull request by joakimrapp**
type.proto is importing any.proto, which is missing in master

### CODE REVIEW

**Comment by joakimrapp** [comment]
i did not patch version, needs to be done before deploy :)

**Comment by joakimrapp** [comment]
i did not patch version, needs to be done before deploy :)

**Comment by joakimrapp** [comment]
continuous-integration/travis-ci/pr failed, i do not understand why, travis config problem?

**Comment by dcodeIO** [comment]
The reason why `any.proto` isn't in there is that it is [already bundled](https://github.com/dcodeIO/protobuf.js/blob/master/src/common.js#L43) with the library. Do you have a use case where this isn't working?

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!

**Pull request closed without merging**
