### PR TITLE
fix RPCImplCallback type declaration - make Error optional

### PR DESCRIPTION
**Pull request by rossenassenov**

### CODE REVIEW

**Comment by dcodeIO** [comment]
index.d.ts is a generated file and any changes will be overwritten on rebuild. Actual source location is: https://github.com/dcodeIO/protobuf.js/blob/master/src/rpc.js#L28

`@param {Error|null}` then, probably.

**Comment by rossenassenov** [comment]
Oh, I see. I wonder why it currently works for the response param, but not the error param ?

**Comment by dcodeIO** [comment]
But is it actually optional? It cannot be `undefined`. There is either an `Error`, or none (`null`).

**Comment by rossenassenov** [comment]
thanks for the fix !

**Pull request closed without merging**
